sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
  wechat:
    appid: wx9acfad86bdb1bd2a
    secret: 9e3ad7c9c787727bd4a84fea1ef06ccf
#    mchid: 1561414331
#    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
#    privateKeyFilePath: C:\software\apiclient_key.pem
#    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    weChatPayCertFilePat: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://17b83ec6.r16.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://17b83ec6.r16.cpolar.top/notify/refundSuccess

#  alioss:
#    endpoint:
#    access-key-id:
#    access-key-secret:
#    bucket-name: